In [1]:
import numpy as np

In [2]:
x=np.array([[1,1,1], [1,2,3]])  
y = np.array([2,4,6])

In [3]:
def updation(w,x,y):
    return 2*(x @ x.T) @ w - 2 * x @ np.expand_dims(y,axis=1)

In [4]:
w_updated,w_ini = np.zeros((2,1)) , np.zeros((2,1))

for i in range(100):
    print(w_ini)
    w_updated = w_ini - (0.1 / 3) * (updation(w_ini,x,y))
    w_ini = w_updated

print(w_updated)

[[0.]
 [0.]]
[[0.8       ]
 [1.86666667]]
[[0.69333333]
 [1.67111111]]
[[0.68622222]
 [1.70074074]]
[[0.66868148]
 [1.70556049]]
[[0.65272099]
 [1.71289811]]
[[0.63701755]
 [1.71977148]]
[[0.62170545]
 [1.72651108]]
[[0.60675993]
 [1.73308523]]
[[0.59217385]
 [1.73950171]]
[[0.57793839]
 [1.74576391]]
[[0.56404515]
 [1.75187557]]
[[0.55048589]
 [1.75784031]]
[[0.53725259]
 [1.76366166]]
[[0.52433741]
 [1.76934307]]
[[0.5117327 ]
 [1.77488791]]
[[0.49943099]
 [1.78029945]]
[[0.48742502]
 [1.7855809 ]]
[[0.47570765]
 [1.79073539]]
[[0.46427197]
 [1.79576596]]
[[0.45311119]
 [1.80067561]]
[[0.44221871]
 [1.80546723]]
[[0.43158807]
 [1.81014367]]
[[0.42121299]
 [1.81470768]]
[[0.41108732]
 [1.81916198]]
[[0.40120506]
 [1.8235092 ]]
[[0.39156037]
 [1.82775192]]
[[0.38214753]
 [1.83189265]]
[[0.37296096]
 [1.83593383]]
[[0.36399524]
 [1.83987787]]
[[0.35524504]
 [1.8437271 ]]
[[0.34670519]
 [1.84748379]]
[[0.33837064]
 [1.85115017]]
[[0.33023644]
 [1.85472842]]
[[0.32229778]
 [1.85822065]]
[

In [5]:
x = np.array([1,15])
x.T @ w_updated

array([29.63787011])